# Generated by Django 5.2.1 on 2025-05-15 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('inventory', models.TextField()),
                ('equipment', models.TextField()),
                ('backstory', models.TextField()),
                ('appearance', models.TextField()),
                ('personality', models.TextField()),
                ('alignment', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('mp', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('luck', models.IntegerField()),
                ('skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_needed', models.IntegerField()),
                ('intelligence_needed', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='MainApp.character')),
            ],
        ),
    ]
