# Generated by Django 5.2.1 on 2025-05-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_remove_weapon_character_character_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_image',
            field=models.ImageField(blank=True, null=True, upload_to='character_images/'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_image',
            field=models.ImageField(blank=True, null=True, upload_to='weapon_images/'),
        ),
    ]
