# Generated by Django 5.2.1 on 2025-05-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_character_character_image_weapon_weapon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/characters'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/weapons'),
        ),
    ]
