# Generated by Django 5.2.1 on 2025-05-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_character_character_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(choices=[('magic', 'Magic'), ('melee', 'Melee'), ('ranged', 'Ranged')], default='melee', max_length=10),
        ),
    ]
