# Generated by Django 5.2.1 on 2025-05-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_weapon_weapon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_image',
            field=models.ImageField(blank=True, null=True, upload_to='characters'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_image',
            field=models.ImageField(blank=True, null=True, upload_to='weapons'),
        ),
    ]
